---

- name: reload systemd
  command: systemctl daemon-reload
  tags:
    - systemd

- name: reload redis
  service: name=redis-server state=restarted

- name: reload redis-sentinel
  service: name=redis-sentinel state=restarted
  when: redis_run_sentinel|bool
